# tls: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
# cert-manager/traefik: https://docs.vultr.com/how-to-install-traefik-ingress-controller-with-cert-manager-on-kubernetes
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: keycloak.sau-portal.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080

  tls:
    - secretName: keycloak-cert
      hosts:
        - keycloak.sau-portal.de
